-- ARES Engine MX baseline.
-- Applies to a new/clean database. Existing pre-MX databases require an explicit data migration before applying this baseline.

CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(180) NOT NULL,
  slug VARCHAR(120) NOT NULL UNIQUE,
  rfc VARCHAR(13) NOT NULL UNIQUE,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT tenant_rfc_mx CHECK (CHAR_LENGTH(rfc) IN (12,13))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  unionId VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(320) NOT NULL UNIQUE,
  password_hash TEXT NULL,
  role ENUM('admin','licitante','proveedor') NOT NULL DEFAULT 'licitante',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  avatar TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  lastSignInAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY users_tenant_id_uq (tenant_id,id),
  KEY users_tenant_idx (tenant_id),
  CONSTRAINT users_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash VARCHAR(128) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  ip_address VARCHAR(64) NULL,
  user_agent TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY sessions_user_idx (user_id),
  KEY sessions_tenant_idx (tenant_id),
  CONSTRAINT sessions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT sessions_user_fk FOREIGN KEY (tenant_id,user_id) REFERENCES users(tenant_id,id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS entidades (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  razon_social VARCHAR(200) NOT NULL,
  nombre_fantasia VARCHAR(200) NULL,
  tipo_entidad ENUM('FEDERAL','ESTATAL','MUNICIPAL','ORGANISMO_AUTONOMO','EMPRESA_PUBLICA') NOT NULL,
  rfc VARCHAR(13) NOT NULL,
  ciudad VARCHAR(100) NULL,
  estado VARCHAR(50) NULL,
  email VARCHAR(150) NULL,
  telefono VARCHAR(30) NULL,
  sitio_web VARCHAR(200) NULL,
  representante_legal VARCHAR(150) NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  verificada BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY entidades_tenant_rfc_uq (tenant_id,rfc),
  UNIQUE KEY entidades_tenant_id_uq (tenant_id,id),
  KEY entidades_tenant_idx (tenant_id),
  CONSTRAINT entidades_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT entidad_rfc_mx CHECK (CHAR_LENGTH(rfc) IN (12,13))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS proveedores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  razon_social VARCHAR(200) NOT NULL,
  nombre_fantasia VARCHAR(200) NULL,
  rfc VARCHAR(13) NOT NULL,
  usuario_id BIGINT UNSIGNED NULL,
  tipo_proveedor ENUM('PERSONA_FISICA','PERSONA_MORAL','COOPERATIVA','CONSORCIO') NOT NULL,
  rubro_principal VARCHAR(100) NOT NULL,
  rubros_secundarios TEXT NULL,
  ciudad VARCHAR(100) NULL,
  estado VARCHAR(50) NULL,
  email VARCHAR(150) NOT NULL,
  telefono VARCHAR(30) NULL,
  sitio_web VARCHAR(200) NULL,
  representante_legal VARCHAR(150) NULL,
  empleados_cantidad INT NULL,
  facturacion_anual DECIMAL(18,2) NULL,
  certificaciones TEXT NULL,
  licitaciones_participadas INT NOT NULL DEFAULT 0,
  licitaciones_ganadas INT NOT NULL DEFAULT 0,
  monto_total_adjudicado DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  calificacion_historica DECIMAL(5,2) NOT NULL DEFAULT 5.00,
  estado_verificacion ENUM('PENDIENTE','EN_REVISION','VERIFICADO','RECHAZADO','SUSPENDIDO') NOT NULL DEFAULT 'PENDIENTE',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY proveedores_tenant_rfc_uq (tenant_id,rfc),
  UNIQUE KEY proveedores_tenant_usuario_uq (tenant_id,usuario_id),
  UNIQUE KEY proveedores_tenant_id_uq (tenant_id,id),
  KEY proveedores_tenant_idx (tenant_id),
  CONSTRAINT proveedores_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT proveedores_tenant_user_fk FOREIGN KEY (tenant_id,usuario_id) REFERENCES users(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT proveedor_rfc_mx CHECK (CHAR_LENGTH(rfc) IN (12,13)),
  CONSTRAINT proveedor_montos_no_negativos CHECK (COALESCE(facturacion_anual,0) >= 0 AND COALESCE(monto_total_adjudicado,0) >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT NULL,
  tipo ENUM('OBRAS','SERVICIOS','BIENES','CONSULTORIA','ARRENDAMIENTOS') NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY categorias_tenant_codigo_uq (tenant_id,codigo),
  UNIQUE KEY categorias_tenant_id_uq (tenant_id,id),
  KEY categorias_tenant_idx (tenant_id),
  CONSTRAINT categorias_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS licitacion_sequences (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  anio INT NOT NULL,
  ultimo_numero INT NOT NULL DEFAULT 0,
  UNIQUE KEY licitacion_sequences_tenant_year_uq (tenant_id,anio),
  CONSTRAINT licitacion_sequences_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT licitacion_sequence_positive CHECK (ultimo_numero >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS licitaciones (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  codigo VARCHAR(50) NOT NULL,
  titulo VARCHAR(300) NOT NULL,
  objeto TEXT NOT NULL,
  descripcion_detallada TEXT NULL,
  estado ENUM('BORRADOR','CONSULTAS','PUBLICADA','EN_EVALUACION','ADJUDICADA','DESIERTA','CANCELADA','FINALIZADA','ARCHIVADA') NOT NULL DEFAULT 'BORRADOR',
  etapa ENUM('PREPARACION','JUNTA_ACLARACIONES','CONVOCATORIA','PRESENTACION','EVALUACION','ADJUDICACION','CONTRATACION','EJECUCION','FINALIZACION') NOT NULL DEFAULT 'PREPARACION',
  entidad_id BIGINT UNSIGNED NOT NULL,
  categoria_id BIGINT UNSIGNED NOT NULL,
  convocante_id BIGINT UNSIGNED NOT NULL,
  tipo_licitacion ENUM('LICITACION_PUBLICA','INVITACION_RESTRINGIDA','ADJUDICACION_DIRECTA') NOT NULL,
  tipo_contratacion ENUM('OBRA','SERVICIO','BIENES','CONCESION','ARRENDAMIENTO') NOT NULL,
  monto_presupuestado DECIMAL(18,2) NOT NULL,
  moneda ENUM('MXN') NOT NULL DEFAULT 'MXN',
  fecha_publicacion DATE NULL,
  fecha_cierre DATE NULL,
  fecha_apertura DATE NULL,
  fecha_adjudicacion DATE NULL,
  criterio_evaluacion ENUM('PRECIO_MAS_BAJO','MEJOR_RELACION_CALIDAD_PRECIO','MEJOR_VALOR_TECNICO') NOT NULL DEFAULT 'MEJOR_RELACION_CALIDAD_PRECIO',
  ponderacion_tecnica DECIMAL(5,2) NOT NULL DEFAULT 40.00,
  ponderacion_economica DECIMAL(5,2) NOT NULL DEFAULT 60.00,
  rubrica_tecnica TEXT NULL,
  modo_evaluacion ENUM('MANUAL','HIBRIDA','AUTOMATICA') NOT NULL DEFAULT 'HIBRIDA',
  proveedor_ganador_id BIGINT UNSIGNED NULL,
  monto_adjudicado DECIMAL(18,2) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY licitaciones_tenant_codigo_uq (tenant_id,codigo),
  UNIQUE KEY licitaciones_tenant_id_uq (tenant_id,id),
  KEY licitaciones_tenant_estado_idx (tenant_id,estado),
  KEY licitaciones_tenant_created_idx (tenant_id,created_at),
  CONSTRAINT licitaciones_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT licitaciones_tenant_entidad_fk FOREIGN KEY (tenant_id,entidad_id) REFERENCES entidades(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT licitaciones_tenant_categoria_fk FOREIGN KEY (tenant_id,categoria_id) REFERENCES categorias(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT licitaciones_tenant_convocante_fk FOREIGN KEY (tenant_id,convocante_id) REFERENCES users(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT licitaciones_tenant_ganador_fk FOREIGN KEY (tenant_id,proveedor_ganador_id) REFERENCES proveedores(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT licitacion_monto_no_negativo CHECK (monto_presupuestado >= 0 AND COALESCE(monto_adjudicado,0) >= 0),
  CONSTRAINT licitacion_ponderaciones_100 CHECK (ponderacion_tecnica + ponderacion_economica = 100),
  CONSTRAINT licitacion_ponderaciones_rango CHECK (ponderacion_tecnica BETWEEN 0 AND 100 AND ponderacion_economica BETWEEN 0 AND 100),
  CONSTRAINT licitacion_fechas_validas CHECK (fecha_cierre IS NULL OR fecha_publicacion IS NULL OR fecha_cierre > fecha_publicacion)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS participaciones (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  licitacion_id BIGINT UNSIGNED NOT NULL,
  proveedor_id BIGINT UNSIGNED NOT NULL,
  monto_oferta DECIMAL(18,2) NOT NULL,
  moneda_oferta ENUM('MXN') NOT NULL DEFAULT 'MXN',
  plazo_ejecucion INT NULL,
  estado_evaluacion ENUM('PENDIENTE','EN_EVALUACION','ADMISIBLE','NO_ADMISIBLE','RECHAZADA','GANADORA','DESCARTADA') NOT NULL DEFAULT 'PENDIENTE',
  puntaje_tecnico DECIMAL(5,2) NULL,
  puntaje_economico DECIMAL(5,2) NULL,
  puntaje_total DECIMAL(6,2) NULL,
  orden_merito INT NULL,
  monto_adjudicado_final DECIMAL(18,2) NULL,
  observaciones TEXT NULL,
  criterios_tecnicos LONGTEXT NULL,
  evaluated_by BIGINT UNSIGNED NULL,
  evaluated_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY participaciones_tenant_licitante_proveedor_uq (tenant_id,licitacion_id,proveedor_id),
  KEY participaciones_tenant_licitacion_idx (tenant_id,licitacion_id),
  CONSTRAINT participaciones_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT participaciones_tenant_licitacion_fk FOREIGN KEY (tenant_id,licitacion_id) REFERENCES licitaciones(tenant_id,id) ON DELETE CASCADE,
  CONSTRAINT participaciones_tenant_proveedor_fk FOREIGN KEY (tenant_id,proveedor_id) REFERENCES proveedores(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT participaciones_tenant_evaluated_fk FOREIGN KEY (tenant_id,evaluated_by) REFERENCES users(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT participacion_monto_no_negativo CHECK (monto_oferta >= 0 AND COALESCE(monto_adjudicado_final,0) >= 0),
  CONSTRAINT participacion_plazo_positivo CHECK (plazo_ejecucion IS NULL OR plazo_ejecucion > 0),
  CONSTRAINT participacion_scores_rango CHECK ((puntaje_tecnico IS NULL OR puntaje_tecnico BETWEEN 0 AND 100) AND (puntaje_economico IS NULL OR puntaje_economico BETWEEN 0 AND 100) AND (puntaje_total IS NULL OR puntaje_total BETWEEN 0 AND 100)),
  CONSTRAINT participacion_monto_adjudicado_no_supera_oferta CHECK (monto_adjudicado_final IS NULL OR monto_adjudicado_final = monto_oferta)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS alertas_seguridad (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  codigo VARCHAR(70) NOT NULL,
  tipo ENUM('ANOMALIA_PRECIO','COLUSION_SOSPECHADA','PATRON_ROTACION','CONFLICTO_INTERES','COMPORTAMIENTO_ANOMALO') NOT NULL,
  severidad ENUM('BAJA','MEDIA','ALTA','CRITICA') NOT NULL,
  score DECIMAL(5,2) NOT NULL DEFAULT 0,
  regla VARCHAR(120) NOT NULL,
  evidencia TEXT NOT NULL,
  licitacion_id BIGINT UNSIGNED NULL,
  proveedor_id BIGINT UNSIGNED NULL,
  descripcion TEXT NOT NULL,
  estado ENUM('NUEVA','INVESTIGANDO','CONFIRMADA','DESCARTADA','RESUELTA') NOT NULL DEFAULT 'NUEVA',
  detectada_automaticamente BOOLEAN NOT NULL DEFAULT TRUE,
  creada_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resuelta_en TIMESTAMP NULL,
  UNIQUE KEY alerta_tenant_codigo_uq (tenant_id,codigo),
  KEY alerta_tenant_status_idx (tenant_id,estado,severidad),
  CONSTRAINT alerta_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT alerta_tenant_licitacion_fk FOREIGN KEY (tenant_id,licitacion_id) REFERENCES licitaciones(tenant_id,id) ON DELETE CASCADE,
  CONSTRAINT alerta_tenant_proveedor_fk FOREIGN KEY (tenant_id,proveedor_id) REFERENCES proveedores(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT alerta_score_rango CHECK (score BETWEEN 0 AND 100)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS documentos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  licitacion_id BIGINT UNSIGNED NULL,
  proveedor_id BIGINT UNSIGNED NULL,
  tipo ENUM('CONVOCATORIA','PLIEGO_TECNICO','PLIEGO_ADMINISTRATIVO','JUNTA_ACLARACIONES','ACTA_APERTURA','OFERTA_TECNICA','OFERTA_ECONOMICA','GARANTIA','ACTA_EVALUACION','DICTAMEN','FALLO_ADJUDICACION','CONTRATO','FACTURA','OTRO') NOT NULL,
  version INT NOT NULL DEFAULT 1,
  nombre_archivo VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  tamano_bytes BIGINT UNSIGNED NOT NULL,
  sha256 VARCHAR(64) NOT NULL,
  storage_key VARCHAR(500) NOT NULL,
  es_publico BOOLEAN NOT NULL DEFAULT FALSE,
  estado ENUM('PENDIENTE','VALIDANDO','APROBADO','RECHAZADO','OBSOLETO') NOT NULL DEFAULT 'PENDIENTE',
  motivo_rechazo TEXT NULL,
  subido_por BIGINT UNSIGNED NOT NULL,
  fecha_subida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY documentos_tenant_storage_uq (tenant_id,storage_key),
  KEY documentos_tenant_licitacion_idx (tenant_id,licitacion_id),
  KEY documentos_tenant_proveedor_idx (tenant_id,proveedor_id),
  CONSTRAINT documentos_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT documentos_tenant_licitacion_fk FOREIGN KEY (tenant_id,licitacion_id) REFERENCES licitaciones(tenant_id,id) ON DELETE CASCADE,
  CONSTRAINT documentos_tenant_proveedor_fk FOREIGN KEY (tenant_id,proveedor_id) REFERENCES proveedores(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT documentos_tenant_user_fk FOREIGN KEY (tenant_id,subido_por) REFERENCES users(tenant_id,id) ON DELETE RESTRICT,
  CONSTRAINT documento_size_positive CHECK (tamano_bytes > 0),
  CONSTRAINT documento_version_positive CHECK (version > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS hitos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  licitacion_id BIGINT UNSIGNED NOT NULL,
  tipo ENUM('PUBLICACION','JUNTA_ACLARACIONES','PREGUNTAS_RESPUESTAS','MODIFICACION_PLIEGO','APERTURA_SOBRES','EVALUACION_TECNICA','EVALUACION_ECONOMICA','FALLO','ADJUDICACION','FIRMA_CONTRATO','INICIO_EJECUCION','ENTREGA','FINALIZACION') NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT NULL,
  fecha_programada TIMESTAMP NOT NULL,
  fecha_realizada TIMESTAMP NULL,
  estado ENUM('PENDIENTE','EN_PROGRESO','COMPLETADO','CANCELADO','RETRASADO') NOT NULL DEFAULT 'PENDIENTE',
  cumplido BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY hitos_tenant_licitacion_idx (tenant_id,licitacion_id,fecha_programada),
  CONSTRAINT hitos_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT hitos_tenant_licitacion_fk FOREIGN KEY (tenant_id,licitacion_id) REFERENCES licitaciones(tenant_id,id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NOT NULL,
  accion VARCHAR(80) NOT NULL,
  entidad VARCHAR(80) NOT NULL,
  entidad_id BIGINT UNSIGNED NULL,
  valor_anterior LONGTEXT NULL,
  valor_nuevo LONGTEXT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_address VARCHAR(64) NULL,
  user_agent TEXT NULL,
  motivo TEXT NULL,
  request_id VARCHAR(80) NULL,
  KEY audit_tenant_entity_idx (tenant_id,entidad,entidad_id),
  KEY audit_tenant_time_idx (tenant_id,timestamp),
  CONSTRAINT audit_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT audit_actor_fk FOREIGN KEY (tenant_id,actor_user_id) REFERENCES users(tenant_id,id) ON DELETE RESTRICT
) ENGINE=InnoDB;
