import { z } from "zod";
import { eq, desc, and, count } from "drizzle-orm";
import { createRouter, adminQuery, capabilityQuery, authedQuery, ctxForAudit } from "../middleware";
import { getDb } from "../queries/connection";
import { alertasSeguridad, licitaciones } from "@db/schema";
import { TRPCError } from "@trpc/server";
import { pageInput, pageResult } from "../lib/pagination";
import { writeAudit } from "../lib/security";
import { detectLicitacionRisks } from "../lib/detection";

export const alertasRouter=createRouter({
  list:authedQuery.input(z.object({estado:z.enum(["NUEVA","INVESTIGANDO","CONFIRMADA","DESCARTADA","RESUELTA"]).optional(),severidad:z.enum(["BAJA","MEDIA","ALTA","CRITICA"]).optional(),page:z.number().int().positive().optional(),pageSize:z.number().int().positive().max(100).optional()}).optional()).query(async({input,ctx})=>{const {page,pageSize,offset}=pageInput(input?.page,input?.pageSize); const c=[eq(alertasSeguridad.tenantId,ctx.user.tenantId)]; if(input?.estado)c.push(eq(alertasSeguridad.estado,input.estado)); if(input?.severidad)c.push(eq(alertasSeguridad.severidad,input.severidad)); const where=and(...c); const db=getDb(); const [items,totalRows]=await Promise.all([db.query.alertasSeguridad.findMany({where,orderBy:[desc(alertasSeguridad.creadaEn)],limit:pageSize,offset,with:{licitacion:true,proveedor:true}}),db.select({total:count()}).from(alertasSeguridad).where(where)]); return pageResult(items,Number(totalRows[0]?.total??0),page,pageSize);}),
  getById:authedQuery.input(z.object({id:z.number().int().positive()})).query(async({input,ctx})=>{const item=await getDb().query.alertasSeguridad.findFirst({where:and(eq(alertasSeguridad.id,input.id),eq(alertasSeguridad.tenantId,ctx.user.tenantId)),with:{licitacion:true,proveedor:true}}); if(!item)throw new TRPCError({code:"NOT_FOUND",message:"Alerta no encontrada."}); return item;}),
  create:adminQuery.input(z.object({tipo:z.enum(["ANOMALIA_PRECIO","COLUSION_SOSPECHADA","PATRON_ROTACION","CONFLICTO_INTERES","COMPORTAMIENTO_ANOMALO"]),severidad:z.enum(["BAJA","MEDIA","ALTA","CRITICA"]),licitacionId:z.number().int().positive().optional(),proveedorId:z.number().int().positive().optional(),descripcion:z.string().trim().min(5),motivo:z.string().trim().min(3)})).mutation(async({input,ctx})=>{const db=getDb(); if(input.licitacionId && !await db.query.licitaciones.findFirst({where:and(eq(licitaciones.id,input.licitacionId),eq(licitaciones.tenantId,ctx.user.tenantId))}))throw new TRPCError({code:"NOT_FOUND",message:"Licitación no encontrada."}); const result=await db.insert(alertasSeguridad).values({tenantId:ctx.user.tenantId,codigo:`ARES-ALT-${new Date().getFullYear()}-${Date.now().toString(36).toUpperCase()}`,tipo:input.tipo,severidad:input.severidad,score:input.severidad==="CRITICA"?"100.00":input.severidad==="ALTA"?"75.00":input.severidad==="MEDIA"?"50.00":"25.00",regla:"MANUAL",evidencia:input.descripcion,licitacionId:input.licitacionId??null,proveedorId:input.proveedorId??null,descripcion:input.descripcion,estado:"NUEVA",detectadaAutomaticamente:false}); const id=Number(result[0].insertId); const created=await db.query.alertasSeguridad.findFirst({where:and(eq(alertasSeguridad.id,id),eq(alertasSeguridad.tenantId,ctx.user.tenantId))}); await writeAudit({ctx:ctxForAudit(ctx),accion:"CREAR",entidad:"alertas_seguridad",entidadId:id,valorNuevo:created,motivo:input.motivo}); return created;}),
  updateEstado:capabilityQuery("auditar").input(z.object({id:z.number().int().positive(),estado:z.enum(["NUEVA","INVESTIGANDO","CONFIRMADA","DESCARTADA","RESUELTA"]),motivo:z.string().trim().min(3)})).mutation(async({input,ctx})=>{const db=getDb(); const current=await db.query.alertasSeguridad.findFirst({where:and(eq(alertasSeguridad.id,input.id),eq(alertasSeguridad.tenantId,ctx.user.tenantId))}); if(!current)throw new TRPCError({code:"NOT_FOUND",message:"Alerta no encontrada."}); const updateData={estado:input.estado,resueltaEn:["RESUELTA","DESCARTADA"].includes(input.estado)?new Date():null}; await db.update(alertasSeguridad).set(updateData).where(and(eq(alertasSeguridad.id,input.id),eq(alertasSeguridad.tenantId,ctx.user.tenantId))); const updated=await db.query.alertasSeguridad.findFirst({where:and(eq(alertasSeguridad.id,input.id),eq(alertasSeguridad.tenantId,ctx.user.tenantId))}); await writeAudit({ctx:ctxForAudit(ctx),accion:"ACTUALIZAR",entidad:"alertas_seguridad",entidadId:input.id,valorAnterior:current,valorNuevo:updated,motivo:input.motivo}); return updated;}),
  detectar:capabilityQuery("auditar").input(z.object({licitacionId:z.number().int().positive(),motivo:z.string().trim().min(3).optional()})).mutation(async({input,ctx})=>{
    const lic=await getDb().query.licitaciones.findFirst({where:and(eq(licitaciones.id,input.licitacionId),eq(licitaciones.tenantId,ctx.user.tenantId))}); if(!lic)throw new TRPCError({code:"NOT_FOUND",message:"Licitación no encontrada."});
    const created=await detectLicitacionRisks(ctx.user.tenantId,lic.id); await writeAudit({ctx:ctxForAudit(ctx),accion:"DETECTAR_RIESGOS",entidad:"licitaciones",entidadId:lic.id,valorNuevo:{alertas:created.length},motivo:input.motivo}); return {alertasCreadas:created.length,alertas:created};
  }),
  countUrgentes:authedQuery.query(async({ctx})=>{const r=await getDb().select({count:count()}).from(alertasSeguridad).where(and(eq(alertasSeguridad.tenantId,ctx.user.tenantId),eq(alertasSeguridad.estado,"NUEVA"))); return Number(r[0]?.count??0);}),
});
