import { z } from "zod";
import { and, count, desc, eq, like } from "drizzle-orm";
import { createRouter, convocanteQuery, adminQuery, ctxForAudit } from "../middleware";
import { getDb } from "../queries/connection";
import { entidades, licitaciones } from "@db/schema";
import { TRPCError } from "@trpc/server";
import { pageInput, pageResult } from "../lib/pagination";
import { writeAudit } from "../lib/security";

const rfcMx=z.string().trim().toUpperCase().regex(/^[A-ZÑ&]{3,4}\d{6}[A-Z0-9]{2,3}$/i,"RFC mexicano inválido.");
export const entidadesRouter=createRouter({
  list:convocanteQuery.input(z.object({search:z.string().trim().optional(),tipo:z.enum(["FEDERAL","ESTATAL","MUNICIPAL","ORGANISMO_AUTONOMO","EMPRESA_PUBLICA"]).optional(),activa:z.boolean().optional(),page:z.number().int().positive().optional(),pageSize:z.number().int().positive().max(100).optional()}).optional()).query(async({input,ctx})=>{const {page,pageSize,offset}=pageInput(input?.page,input?.pageSize); const c=[eq(entidades.tenantId,ctx.user.tenantId)]; if(input?.search)c.push(like(entidades.razonSocial,`%${input.search}%`)); if(input?.tipo)c.push(eq(entidades.tipoEntidad,input.tipo)); if(input?.activa!==undefined)c.push(eq(entidades.activa,input.activa)); const where=and(...c); const db=getDb(); const [items,totalRows]=await Promise.all([db.query.entidades.findMany({where,orderBy:[desc(entidades.createdAt)],limit:pageSize,offset}),db.select({total:count()}).from(entidades).where(where)]); return pageResult(items,Number(totalRows[0]?.total??0),page,pageSize);}),
  getById:convocanteQuery.input(z.object({id:z.number().int().positive()})).query(async({input,ctx})=>{const item=await getDb().query.entidades.findFirst({where:and(eq(entidades.id,input.id),eq(entidades.tenantId,ctx.user.tenantId))});if(!item)throw new TRPCError({code:"NOT_FOUND",message:"Entidad no encontrada."});return item;}),
  create:convocanteQuery.input(z.object({razonSocial:z.string().trim().min(3).max(200),nombreFantasia:z.string().trim().optional(),tipoEntidad:z.enum(["FEDERAL","ESTATAL","MUNICIPAL","ORGANISMO_AUTONOMO","EMPRESA_PUBLICA"]),rfc:rfcMx,ciudad:z.string().trim().optional(),estado:z.string().trim().optional(),email:z.string().email().optional(),telefono:z.string().optional(),sitioWeb:z.string().url().optional(),representanteLegal:z.string().trim().optional()})).mutation(async({input,ctx})=>{const db=getDb(); const duplicate=await db.query.entidades.findFirst({where:and(eq(entidades.tenantId,ctx.user.tenantId),eq(entidades.rfc,input.rfc))});if(duplicate)throw new TRPCError({code:"CONFLICT",message:"El RFC ya está registrado en este tenant."});const result=await db.insert(entidades).values({tenantId:ctx.user.tenantId,...input,activa:true,verificada:false});const id=Number(result[0].insertId);const created=await db.query.entidades.findFirst({where:and(eq(entidades.id,id),eq(entidades.tenantId,ctx.user.tenantId))});await writeAudit({ctx:ctxForAudit(ctx),accion:"CREAR",entidad:"entidades",entidadId:id,valorNuevo:created});return created;}),
  update:convocanteQuery.input(z.object({id:z.number().int().positive(),razonSocial:z.string().trim().min(3).optional(),nombreFantasia:z.string().trim().nullable().optional(),tipoEntidad:z.enum(["FEDERAL","ESTATAL","MUNICIPAL","ORGANISMO_AUTONOMO","EMPRESA_PUBLICA"]).optional(),rfc:rfcMx.optional(),ciudad:z.string().trim().nullable().optional(),estado:z.string().trim().nullable().optional(),email:z.string().email().nullable().optional(),telefono:z.string().nullable().optional(),sitioWeb:z.string().url().nullable().optional(),representanteLegal:z.string().trim().nullable().optional(),activa:z.boolean().optional(),verificada:z.boolean().optional(),motivo:z.string().trim().min(3)})).mutation(async({input,ctx})=>{const db=getDb();const current=await db.query.entidades.findFirst({where:and(eq(entidades.id,input.id),eq(entidades.tenantId,ctx.user.tenantId))});if(!current)throw new TRPCError({code:"NOT_FOUND",message:"Entidad no encontrada."});const {id,motivo,...data}=input;await db.update(entidades).set(data).where(and(eq(entidades.id,id),eq(entidades.tenantId,ctx.user.tenantId)));const updated=await db.query.entidades.findFirst({where:and(eq(entidades.id,id),eq(entidades.tenantId,ctx.user.tenantId))});await writeAudit({ctx:ctxForAudit(ctx),accion:"ACTUALIZAR",entidad:"entidades",entidadId:id,valorAnterior:current,valorNuevo:updated,motivo});return updated;}),
  delete:adminQuery.input(z.object({id:z.number().int().positive(),motivo:z.string().trim().min(3)})).mutation(async({input,ctx})=>{const db=getDb();const current=await db.query.entidades.findFirst({where:and(eq(entidades.id,input.id),eq(entidades.tenantId,ctx.user.tenantId))});if(!current)throw new TRPCError({code:"NOT_FOUND",message:"Entidad no encontrada."});const refs=await db.query.licitaciones.findFirst({where:and(eq(licitaciones.tenantId,ctx.user.tenantId),eq(licitaciones.entidadId,input.id))});if(refs)throw new TRPCError({code:"CONFLICT",message:"No se puede eliminar una entidad usada por una licitación."});await db.delete(entidades).where(and(eq(entidades.id,input.id),eq(entidades.tenantId,ctx.user.tenantId)));await writeAudit({ctx:ctxForAudit(ctx),accion:"ELIMINAR",entidad:"entidades",entidadId:input.id,valorAnterior:current,motivo:input.motivo});return {success:true};}),
});
